/* Fort Merle: everything is cached on the first visit, so the game runs with no network at all. */
const CACHE = "fort-merle-v5";
const ASSETS = [
 "./",
 "index.html",
 "manifest.webmanifest",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/apple-touch-icon.png",
 "art/caught.jpg",
 "art/cave0.jpg",
 "art/cave1.jpg",
 "art/cave2.jpg",
 "art/cave3.jpg",
 "art/cave4.jpg",
 "art/cave5.jpg",
 "art/cell.jpg",
 "art/chapel.jpg",
 "art/corridor.jpg",
 "art/dawn.jpg",
 "art/drowned.jpg",
 "art/fort.jpg",
 "art/i_canvas.jpg",
 "art/i_pitch.jpg",
 "art/i_planks.jpg",
 "art/i_rope.jpg",
 "art/i_tools.jpg",
 "art/kitchen.jpg",
 "art/laundry.jpg",
 "art/map.jpg",
 "art/p_cook.jpg",
 "art/p_foreman.jpg",
 "art/p_governor.jpg",
 "art/p_kessel.jpg",
 "art/p_laundress.jpg",
 "art/p_voss.jpg",
 "art/p_warder.jpg",
 "art/sea.jpg",
 "art/transfer.jpg",
 "art/v_beam.jpg",
 "art/v_canvas.jpg",
 "art/v_carry.jpg",
 "art/v_launch.jpg",
 "art/v_listen.jpg",
 "art/v_pitch.jpg",
 "art/v_planks.jpg",
 "art/v_rope.jpg",
 "art/v_storm.jpg",
 "art/v_tools.jpg",
 "art/wall.jpg",
 "art/workshop.jpg",
 "art/yard.jpg",
 "voice/c_foreman_planks.mp3",
 "voice/c_foreman_tools.mp3",
 "voice/c_governor.mp3",
 "voice/c_kessel.mp3",
 "voice/c_laundress.mp3",
 "voice/c_voss_build.mp3",
 "voice/c_voss_intro.mp3",
 "voice/c_voss_launch.mp3",
 "voice/c_warder_beam.mp3",
 "voice/c_warder_count.mp3",
 "voice/c_warder_door.mp3",
 "voice/c_warder_sea.mp3",
 "voice/c_warder_transfer.mp3",
 "voice/characters.json",
 "voice/n00.mp3",
 "voice/n01.mp3",
 "voice/n02.mp3",
 "voice/n03.mp3",
 "voice/n04.mp3",
 "voice/n05.mp3",
 "voice/n06.mp3",
 "voice/n07.mp3",
 "voice/n08.mp3",
 "voice/n09.mp3",
 "voice/n10.mp3",
 "voice/n11.mp3",
 "voice/n12.mp3",
 "voice/n13.mp3",
 "voice/n14.mp3",
 "voice/n15.mp3",
 "voice/n16.mp3",
 "voice/n17.mp3",
 "voice/n17b.mp3",
 "voice/n18.mp3",
 "voice/n19.mp3",
 "voice/n20.mp3",
 "voice/n21.mp3",
 "voice/n22.mp3",
 "voice/n23.mp3",
 "voice/n24.mp3",
 "voice/n25.mp3",
 "voice/n26.mp3",
 "voice/n27.mp3",
 "voice/n28.mp3",
 "voice/n29.mp3",
 "voice/n30.mp3",
 "voice/n31.mp3",
 "voice/n32.mp3",
 "voice/n33.mp3",
 "voice/n34.mp3",
 "voice/n35.mp3",
 "voice/n36.mp3",
 "voice/n37.mp3",
 "voice/n38.mp3",
 "voice/n39.mp3",
 "voice/n40.mp3",
 "voice/n41.mp3",
 "voice/n42.mp3",
 "voice/n43.mp3",
 "voice/n44.mp3",
 "voice/n45.mp3",
 "voice/n46.mp3",
 "voice/n47.mp3",
 "voice/n48.mp3"
];
self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).then(res => {
    const copy = res.clone();
    caches.open(CACHE).then(c => c.put(e.request, copy)).catch(() => {});
    return res;
  }).catch(() => caches.match("index.html"))));
});
